---
- hostname: "server1"
  connection: ssh
  server: "127.0.0.1"
  port: 22
  user: "root"
  password: ""
  keyfile: "id_rsa"
  env: prod
  desc: "This is a first server"	

- hostname: "testServer"
  connection: ssh
  server: 192.168.1.1
  env: test 
  user: test
  password: "test"

- hostname: "ubuntu"
  connection: local
  env: dev
